# Generated by Django 3.0.7 on 2020-06-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_img', models.ImageField(upload_to='pics')),
                ('image_alt', models.CharField(max_length=15)),
                ('carousel_desc', models.CharField(max_length=35)),
            ],
        ),
    ]
